---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: clickhouse
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  teknoir.xml: |
    <clickhouse>
        <allow_disk_based_merge>true</allow_disk_based_merge>

        <prometheus>
            <endpoint>/metrics</endpoint>
            <port>9363</port>
            <metrics>true</metrics>
            <events>true</events>
            <asynchronous_metrics>true</asynchronous_metrics>
        </prometheus>

        <logger>
            <!-- Logging level can be "trace", "debug", "information", "warning", or "error" -->
            <level>{{ .Values.config.logLevel }}</level>
            <log_to_console>true</log_to_console>
            <console>1</console>
            <log_to_syslog>false</log_to_syslog>
        </logger>
    </clickhouse>