---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: clickhouse
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  teknoir.xml: |
    {{- .Values.config | nindent 4 }}
