---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: clickhouse
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  teknoir.xml: |
    <clickhouse>
        <allow_disk_based_merge>true</allow_disk_based_merge>

        <prometheus>
            <endpoint>/metrics</endpoint>
            <port>9363</port>
            <metrics>true</metrics>
            <events>true</events>
            <asynchronous_metrics>true</asynchronous_metrics>
        </prometheus>
    </clickhouse>