---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-users
  namespace: {{ .Release.Namespace }}
  labels:
    app: clickhouse
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  teknoir.xml: |
    <clickhouse>
        <profiles>
            <default>
                <max_memory_usage>2147483648</max_memory_usage>
            </default>
        </profiles>
    </clickhouse>
