# ClickhouseDB container configuration
image:
  repository: clickhouse/clickhouse-server
  tag: "24.8.11-alpine"
  pullPolicy: Always

# Resource requests and limits
resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 5Gi
    cpu: 1500m

# Service configuration
nodePort:
  enabled: false

annotations:
  teknoir.org/managed-by: devstudio

# Configuration for the ClickhouseDB server
config: |-
  <clickhouse>
      <allow_disk_based_merge>true</allow_disk_based_merge>

      <prometheus>
          <endpoint>/metrics</endpoint>
          <port>9363</port>
          <metrics>true</metrics>
          <events>true</events>
          <asynchronous_metrics>true</asynchronous_metrics>
      </prometheus>

      <logger>
          <level>information</level>
          <log_to_console>true</log_to_console>
          <console>1</console>
          <log_to_syslog>false</log_to_syslog>
      </logger>

      <query_log replace="1">
        <database>system</database>
        <table>query_log</table>
        <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 7 day</engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
      </query_log>
      
      <processors_profile_log replace="1">
        <database>system</database>
        <table>processors_profile_log</table>
        <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 7 day</engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
      </processors_profile_log>
      
      <trace_log replace="1">
        <database>system</database>
        <table>trace_log</table>
        <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 7 day</engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
      </trace_log>
      
      <part_log replace="1">
        <database>system</database>
        <table>part_log</table>
        <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
      </part_log>
      
      <asynchronous_metric_log replace="1">
        <database>system</database>
        <table>asynchronous_metric_log</table>
        <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
      </asynchronous_metric_log>
      
      <metric_log replace="1">
        <database>system</database>
        <table>metric_log</table>
        <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + INTERVAL 30 day</engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
      </metric_log>

  </clickhouse>

user: |-
  <clickhouse>
      <profiles>
          <default>
              <max_memory_usage>4000000000</max_memory_usage>
              <max_memory_usage_for_user>4500000000</max_memory_usage_for_user>
          </default>
      </profiles>
  </clickhouse>