# ClickhouseDB container configuration
image:
  repository: clickhouse/clickhouse-server
  tag: "24.8.11-alpine"
  pullPolicy: Always

# Resource requests and limits
resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 5Gi
    cpu: 1500m

# Service configuration
nodePort:
  enabled: false

annotations:
  teknoir.org/managed-by: devstudio

